name: Scrape

on: 
   - push
   - pull_request
   
jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build Docker image
        run: |
          docker build -t docker_image .
